### ISSUE TITLE
failed to load 'plugin.py'

### ISSUE THREAD

**Issue by roblomq** [moroen/ZWave-MQTT-plugin#29]
Hello

I'm trying to get the Zwave2MQTT plugin running but I think there is something wrong. At startup of the plugin I get in the domoticz log the error messages below .

`2022-07-24 02:07:08.032 Error: Zwave2MQTT plugin: (ZWave-MQTT) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/ZWave-MQTT/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
2022-07-24 02:07:08.066 Error: Zwave2MQTT plugin: Traceback (most recent call last):
2022-07-24 02:07:08.066 Error: Zwave2MQTT plugin: File "/home/pi/domoticz/plugins/ZWave-MQTT/plugin.py", line 58, in <module>
2022-07-24 02:07:08.066 Error: Zwave2MQTT plugin: import api.devices
2022-07-24 02:07:08.066 Error: Zwave2MQTT plugin: File "/home/pi/domoticz/plugins/ZWave-MQTT/api/devices.py", line 6, in <module>
2022-07-24 02:07:08.066 Error: Zwave2MQTT plugin: from .device_types import (
2022-07-24 02:07:08.066 Error: Zwave2MQTT plugin: File "/home/pi/domoticz/plugins/ZWave-MQTT/api/device_types.py", line 5, in <module>
2022-07-24 02:07:08.066 Error: Zwave2MQTT plugin: from .config import get_global_device_types_filename, get_user_device_types_filename
2022-07-24 02:07:08.066 Error: Zwave2MQTT plugin: File "/home/pi/domoticz/plugins/ZWave-MQTT/api/config.py", line 1, in <module>
2022-07-24 02:07:08.066 Error: Zwave2MQTT plugin: from yaml import load, FullLoader
2022-07-24 02:07:08.066 Error: Zwave2MQTT plugin: ModuleNotFoundError: No module named 'yaml'`

I'm running the latest beta 

Version: 2022.1 (build 14420)
Build Hash: 81ce5798b
Compile Date: 2022-07-22 12:02:09
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

**Comment by heggink** [comment]
This plugin is no longer maintained. You are advised to use the native domoticz autodiscovery functionality.

**Comment by roblomq** [comment]
That makes sense :-) thanks for the info, I will switch to de native one.

**Comment by roblomq** [comment]
The uninstall instructions are missing in the wiki :-)
